
def identity():
    return "CottonCandy"

def ColorDictionary():
    return {
    "padx" : 5,
    "pady" : 5,
    "bg" : "#A30086",
    "txt_bg" : "#A30086",
    "txt_fg" : "#FFC1F4",
    "btn_bg" : "#5E004D",
    "btn_fg" : "#FFC1F4",
    "btn_alt_bg" : "#FFC1F4",
    "btn_alt_fg" : "#5E004D",

    "fileio_padx" : 5,
    "fileio_pady" : 5,
    "fileio_bg" : "#A30086",
    "fileio_txt_bg" : "#A30086",
    "fileio_txt_fg" : "#FFC1F4",
    "fileio_btn_bg" : "#8C0073",
    "fileio_btn_fg" : "#FF76E6",
    "fileio_btn_alt_bg" : "#FFC1F4",
    "fileio_btn_alt_fg" : "#5E004D",

    "node_padx" : 5,
    "node_pady" : 5,
    "node_bg" : "#E800BF",
    "node_txt_bg" : "#E800BF",
    "node_txt_fg" : "#FFC1F4",
    "node_ent_bg" : "#5E004D",
    "node_ent_fg" : "#FFC1F4",
    "node_btn_bg" : "#8C0073",
    "node_btn_fg" : "#FF76E6",
    "node_btn_alt_bg" : "#FF76E6",
    "node_btn_alt_fg" : "#8C0073",

    "performance_padx" : 5,
    "performance_pady" : 5,
    "performance_bg" : "#E800BF",
    "performance_txt_bg" : "#E800BF",
    "performance_txt_fg" : "#FFC1F4",
    "performance_ent_bg" : "#5E004D",
    "performance_ent_fg" : "#FFC1F4",
    "performance_btn_bg" : "#8C0073",
    "performance_btn_fg" : "#FF76E6",
    "performance_btn_alt_bg" : "#FF76E6",
    "performance_btn_alt_fg" : "#8C0073",

    "network_padx" : 5,
    "network_pady" : 5,
    "network_bg" : "#E800BF",
    "network_txt_bg" : "#E800BF",
    "network_txt_fg" : "#FFC1F4",
    "network_ent_bg" : "#5E004D",
    "network_ent_fg" : "#FFC1F4",
    "network_btn_bg" : "#8C0073",
    "network_btn_fg" : "#FF76E6",
    "network_btn_alt_bg" : "#FF76E6",
    "network_btn_alt_fg" : "#8C0073",

    "ups_padx" : 5,
    "ups_pady" : 5,
    "ups_bg" : "#E800BF",
    "ups_txt_bg" : "#E800BF",
    "ups_txt_fg" : "#FFC1F4",
    "ups_ent_bg" : "#5E004D",
    "ups_ent_fg" : "#FFC1F4",
    "ups_btn_bg" : "#8C0073",
    "ups_btn_fg" : "#FF76E6",
    "ups_btn_alt_bg" : "#FF76E6",
    "ups_btn_alt_fg" : "#8C0073",

    "design_padx" : 5,
    "design_pady" : 5,
    "design_bg" : "#E800BF",
    "design_txt_bg" : "#E800BF",
    "design_txt_fg" : "#FFC1F4",
    "design_ent_bg" : "#5E004D",
    "design_ent_fg" : "#FFC1F4",
    "design_btn_bg" : "#8C0073",
    "design_btn_fg" : "#FF76E6",
    "design_btn_alt_bg" : "#FF76E6",
    "design_btn_alt_fg" : "#8C0073",

    "settings_padx" : 5,
    "settings_pady" : 5,
    "settings_bg" : "#E800BF",
    "settings_txt_bg" : "#E800BF",
    "settings_txt_fg" : "#FFC1F4",
    "settings_ent_bg" : "#5E004D",
    "settings_ent_fg" : "#FFC1F4",
    "settings_btn_bg" : "#8C0073",
    "settings_btn_fg" : "#FF76E6",
    "settings_btn_alt_bg" : "#FF76E6",
    "settings_btn_alt_fg" : "#8C0073",

    "about_padx" : 5,
    "about_pady" : 5,
    "about_bg" : "#E800BF",
    "about_txt_bg" : "#E800BF",
    "about_txt_fg" : "#FFC1F4",
    "about_ent_bg" : "#5E004D",
    "about_ent_fg" : "#FFC1F4",
    "about_btn_bg" : "#8C0073",
    "about_btn_fg" : "#FF76E6",
    "about_btn_alt_bg" : "#FF76E6",
    "about_btn_alt_fg" : "#8C0073"
}
