def identity():
    print("Light_1 is currently not properly impolements, Completion: TBD")
    return "Light_1"
def ColorDictionary():
    return {
        "padx" : 5,
        "pady" : 5,
        "bg" : "#EBEBEB",
        "txt_fg" : "#323232",
        "txt_bg" : "#EBEBEB",
        "btn_fg" : "#1E1E1E",
        "btn_bg" : "#EBEBEB",
        "btn_alt_fg" : "#EBEBEB",
        "btn_alt_bg" : "#1E1E1E",

        "fileio_padx" : 5,
        "fileio_pady" : 5,
        "fileio_bg" : "#EBEBEB",
        "fileio_txt_fg" : "#323232",
        "fileio_txt_bg" : "#EBEBEB",
        "fileio_btn_fg" : "#1E1E1E",
        "fileio_btn_bg" : "#EBEBEB",
        "fileio_btn_alt_fg" : "#EBEBEB",
        "fileio_btn_alt_bg" : "#1E1E1E",

        "node_padx" : 5,
        "node_pady" : 5,
        "node_bg" : "#EBEBEB",
        "node_txt_fg" : "#3C3C3C",
        "node_txt_bg" : "#EBEBEB",
        "node_ent_fg" : "#1E1E1E",
        "node_ent_bg" : "#EBEBEB",
        "node_btn_fg" : "#444444",
        "node_btn_bg" : "#CCCCCC",
        "node_btn_alt_fg" : "#CCCCCC",
        "node_btn_alt_bg" : "#444444",

        "performance_padx" : 5,
        "performance_pady" : 5,
        "performance_bg" : "#EBEBEB",
        "performance_txt_fg" : "#3C3C3C",
        "performance_txt_bg" : "#EBEBEB",
        "performance_ent_fg" : "#1E1E1E",
        "performance_ent_bg" : "#EBEBEB",
        "performance_btn_fg" : "#444444",
        "performance_btn_bg" : "#CCCCCC",
        "performance_btn_alt_fg" : "#CCCCCC",
        "performance_btn_alt_bg" : "#444444",

        "network_padx" : 5,
        "network_pady" : 5,
        "network_bg" : "#EBEBEB",
        "network_txt_fg" : "#3C3C3C",
        "network_txt_bg" : "#EBEBEB",
        "network_ent_fg" : "#1E1E1E",
        "network_ent_bg" : "#EBEBEB",
        "network_btn_fg" : "#444444",
        "network_btn_bg" : "#CCCCCC",
        "network_btn_alt_fg" : "#CCCCCC",
        "network_btn_alt_bg" : "#444444",

        "ups_padx" : 5,
        "ups_pady" : 5,
        "ups_bg" : "#EBEBEB",
        "ups_txt_fg" : "#3C3C3C",
        "ups_txt_bg" : "#EBEBEB",
        "ups_ent_fg" : "#1E1E1E",
        "ups_ent_bg" : "#EBEBEB",
        "ups_btn_fg" : "#444444",
        "ups_btn_bg" : "#CCCCCC",
        "ups_btn_alt_fg" : "#CCCCCC",
        "ups_btn_alt_bg" : "#444444",

        "design_padx" : 5,
        "design_pady" : 5,
        "design_bg" : "#EBEBEB",
        "design_txt_fg" : "#3C3C3C",
        "design_txt_bg" : "#EBEBEB",
        "design_ent_fg" : "#1E1E1E",
        "design_ent_bg" : "#EBEBEB",
        "design_btn_fg" : "#444444",
        "design_btn_bg" : "#CCCCCC",
        "design_btn_alt_fg" : "#CCCCCC",
        "design_btn_alt_bg" : "#444444",

        "settings_padx" : 5,
        "settings_pady" : 5,
        "settings_bg" : "#EBEBEB",
        "settings_txt_fg" : "#3C3C3C",
        "settings_txt_bg" : "#EBEBEB",
        "settings_ent_fg" : "#1E1E1E",
        "settings_ent_bg" : "#EBEBEB",
        "settings_btn_fg" : "#444444",
        "settings_btn_bg" : "#CCCCCC",
        "settings_btn_alt_fg" : "#CCCCCC",
        "settings_btn_alt_bg" : "#444444",

        "about_padx" : 5,
        "about_pady" : 5,
        "about_bg" : "#EBEBEB",
        "about_txt_fg" : "#3C3C3C",
        "about_txt_bg" : "#EBEBEB",
        "about_ent_fg" : "#1E1E1E",
        "about_ent_bg" : "#EBEBEB",
        "about_btn_fg" : "#444444",
        "about_btn_bg" : "#CCCCCC",
        "about_btn_alt_fg" : "#CCCCCC",
        "about_btn_alt_bg" : "#444444"
    }
