publish	:
	-mkdir -p ../published/src/webserverhome
	cp Makefile make.bat publish_src.bat publish_bin.bat cgiwebserver.py favicon.ico index-linux.html index-win.html start.html startwebserver.bat startwebserver.sh ../published/src/webserverhome
	-mkdir -p ../published/bin/webserverhome
	cp cgiwebserver.py favicon.ico index-linux.html index-win.html start.html startwebserver.bat startwebserver.sh ../published/bin/webserverhome
