publish	:
	-mkdir -p ../published/src/floorplan
	cp -r Makefile make.bat publish_src.bat publish_bin.bat cgi-bin ../published/src/floorplan
	-mkdir -p ../published/bin/webserverhome/cgi-bin/floorplan
	cp cgi-bin/* ../published/bin/webserverhome/cgi-bin/floorplan
