publish	:
	-mkdir -p ../published/src/ups
	cp -r Makefile make.bat publish_src.bat publish_bin.bat cgi-bin ../published/src/ups
	-mkdir -p ../published/bin/webserverhome/cgi-bin/ups
	cp -r cgi-bin/* ../published/bin/webserverhome/cgi-bin/ups
